src/Richpolis/UsuariosBundle/Entity/Hijo.php
<?php

namespace Richpolis\UsuariosBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Hijo
 *
 * @ORM\Table(name="hijos")
 * @ORM\Entity(repositoryClass="Richpolis\UsuariosBundle\Entity\HijoRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Hijo
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="apodo", type="string", length=255,nullable=true)
     */
    private $apodo;

    /**
     * @var boolean
     *
     * @ORM\Column(name="usarApodo", type="boolean")
     */
    private $usarApodo;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="sexo", type="integer")
     */
    private $sexo;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="fechaNacimiento", type="date")
     */
    private $fechaNacimiento;

    /**
     * @var string
     *
     * @ORM\Column(name="biografia", type="text",nullable=true)
     */
    private $biografia;

    /**
     * @var string
     *
     * @ORM\Column(name="imagen", type="string", length=255, nullable=true)
     */
    private $imagen;

    /**
     * @var \Richpolis\UsuariosBundle\Entity\Usuario
     *
     * @ORM\ManyToOne(targetEntity="Richpolis\UsuariosBundle\Entity\Usuario", inversedBy="hijos")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="papa_id", referencedColumnName="id")
     * })
     */
    private $papa;
    
   
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=false)
     */
    private $updatedAt;
    
    
    const INDEFINIDO = 0;
    const NINO = 1;
    const NINA = 2;
    
    static public $sSexo=array(
        self::INDEFINIDO=>'Es niño o niña?',
        self::NINO=>'Niño',
        self::NINA=>'Niña',
    );
    
    public function __construct() {
        $this->sexo= self::INDEFINIDO;
        $this->usarApodo = true;
        $this->fechaNacimiento = new \DateTime();
    }
    
    public function getStringSexo(){
        return self::$sSexo[$this->getSexo()];
    }

    static function getArraySexo(){
        return self::$sSexo;
    }

    static function getPreferedSexo(){
        return array(self::INDEFINIDO);
    }

    public function __toString() {
        if($this->usarApodo){
            return $this->getApodo();
        }else{
            return $this->getNombre();
        }
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Hijo
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set apodo
     *
     * @param string $apodo
     * @return Hijo
     */
    public function setApodo($apodo)
    {
        $this->apodo = $apodo;

        return $this;
    }

    /**
     * Get apodo
     *
     * @return string 
     */
    public function getApodo()
    {
        return $this->apodo;
    }

    /**
     * Set usarApodo
     *
     * @param boolean $usarApodo
     * @return Hijo
     */
    public function setUsarApodo($usarApodo)
    {
        $this->usarApodo = $usarApodo;

        return $this;
    }

    /**
     * Get usarApodo
     *
     * @return boolean 
     */
    public function getUsarApodo()
    {
        return $this->usarApodo;
    }
    
    /**
     * @Assert\True(message = "Ingresar el apodo.")
     */
    public function isUsarApodoValid()
    {
        if($this->getUsarApodo()){
            return strlen(trim($this->getApodo()))>0;
        }
        return true;
    }

    /**
     * Set fechaNacimiento
     *
     * @param \DateTime $fechaNacimiento
     * @return Hijo
     */
    public function setFechaNacimiento($fechaNacimiento)
    {
        $this->fechaNacimiento = $fechaNacimiento;

        return $this;
    }

    /**
     * Get fechaNacimiento
     *
     * @return \DateTime 
     */
    public function getFechaNacimiento()
    {
        return $this->fechaNacimiento;
    }

    /**
     * Set biografia
     *
     * @param string $biografia
     * @return Hijo
     */
    public function setBiografia($biografia)
    {
        $this->biografia = $biografia;

        return $this;
    }

    /**
     * Get biografia
     *
     * @return string 
     */
    public function getBiografia()
    {
        return $this->biografia;
    }

    /**
     * Set imagen
     *
     * @param string $imagen
     * @return Hijo
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * Get imagen
     *
     * @return string 
     */
    public function getImagen()
    {
        return $this->imagen;
    }

    /**
     * Set papa
     *
     * @param \Richpolis\UsuariosBundle\Entity\Usuario $papa
     * @return Hijo
     */
    public function setPapa(\Richpolis\UsuariosBundle\Entity\Usuario $papa = null)
    {
        $this->papa = $papa;

        return $this;
    }

    /**
     * Get papa
     *
     * @return \Richpolis\UsuariosBundle\Entity\Usuario 
     */
    public function getPapa()
    {
        return $this->papa;
    }
    
    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Hijo
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Hijo
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set sexo
     *
     * @param integer $sexo
     * @return Hijo
     */
    public function setSexo($sexo)
    {
        $this->sexo = $sexo;

        return $this;
    }

    /**
     * Get sexo
     *
     * @return integer 
     */
    public function getSexo()
    {
        return $this->sexo;
    }
    
    /*
     * Timestable
     */
    
    /**
     ** @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        if(!$this->getCreatedAt())
        {
          $this->createdAt = new \DateTime();
        }
        if(!$this->getUpdatedAt())
        {
          $this->updatedAt = new \DateTime();
        }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }
    
    /*** uploads ***/
    
    /**
     * @Assert\File(maxSize="2M",maxSizeMessage="El archivo es demasiado grande. El tamaño máximo permitido es {{ limit }}")
     */
    public $file;
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->imagen)) {
            // store the old name to delete after the update
            $this->temp = $this->imagen;
            $this->imagen = null;
        } else {
            $this->imagen = 'initial';
        }
    }
    
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preUpload()
    {
      if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->imagen = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
    * @ORM\PostPersist
    * @ORM\PostUpdate
    */
    public function upload()
    {
      if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->imagen);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            if(file_exists($this->getUploadRootDir().'/'.$this->temp)){
                unlink($this->getUploadRootDir().'/'.$this->temp);
            }
            $this->temp = null;
        }
        
        $this->crearThumbnail();
        
        $this->file = null;
    }
    
    /*
     * Crea el thumbnail y lo guarda en un carpeta dentro del webPath thumbnails
     * 
     * @return void
     */
    public function crearThumbnail($width=100,$height=100,$path=""){
        $imagine    = new \Imagine\Gd\Imagine();
        $collage    = $imagine->create(new \Imagine\Image\Box(100, 100));
        $mode       = \Imagine\Image\ImageInterface::THUMBNAIL_INSET;
        $image      = $imagine->open($this->getAbsolutePath());
        $sizeImage  = $image->getSize();
        if(strlen($path)==0){
            $path = $this->getAbosluteThumbnailPath();
        }
        if($height == null){

src/Richpolis/UsuariosBundle/Controller/HijoController.php
<?php

namespace Richpolis\UsuariosBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Richpolis\UsuariosBundle\Entity\Hijo;
use Richpolis\UsuariosBundle\Form\HijoType;

/**
 * Hijo controller.
 *
 * @Route("/admin/hijos")
 */
class HijoController extends Controller
{

    /**
     * Lists all Hijo entities.
     *
     * @Route("/", name="hijos")
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $buscar = $request->get('buscar','');
        if(strlen($buscar)>0){
                $options = array('filterParam'=>'buscar','filterValue'=>$buscar);
        }else{
                $options = array();
        }
        $query = $em->getRepository('UsuariosBundle:Hijo')->queryFindHijos($buscar);
        $paginator = $this->get('knp_paginator');
        $pagination = $paginator->paginate(
                $query, $this->get('request')->query->get('page', 1),10, $options 
        );

        return compact('pagination');
    }
    /**
     * Creates a new Hijo entity.
     *
     * @Route("/", name="hijos_create")
     * @Method("POST")
     * @Template("UsuariosBundle:Hijo:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Hijo();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('hijos_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Hijo entity.
     *
     * @param Hijo $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Hijo $entity)
    {
        $form = $this->createForm(new HijoType(), $entity, array(
            'action' => $this->generateUrl('hijos_create'),
            'method' => 'POST',
        ));

        //$form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Hijo entity.
     *
     * @Route("/new", name="hijos_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Hijo();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Hijo entity.
     *
     * @Route("/{id}", name="hijos_show", requirements={"id": "\d+"})
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('UsuariosBundle:Hijo')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Hijo entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Hijo entity.
     *
     * @Route("/{id}/edit", name="hijos_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('UsuariosBundle:Hijo')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Hijo entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Hijo entity.
    *
    * @param Hijo $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Hijo $entity)
    {
        $form = $this->createForm(new HijoType(), $entity, array(
            'action' => $this->generateUrl('hijos_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        //$form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Hijo entity.
     *
     * @Route("/{id}", name="hijos_update")
     * @Method("PUT")
     * @Template("UsuariosBundle:Hijo:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('UsuariosBundle:Hijo')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Hijo entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('hijos_edit', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Hijo entity.
     *
     * @Route("/{id}", name="hijos_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('UsuariosBundle:Hijo')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Hijo entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('hijos'));
    }

    /**
     * Creates a form to delete a Hijo entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('hijos_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Eliminar','attr'=>array('class'=>'btn btn-danger')))
            ->getForm()
        ;
    }
    
    /**
     * Exporta la lista completa de hijos.
     *
     * @Route("/exportar", name="hijos_export")
     * @Method("GET")
     */
    public function exportarAction() {
        $hijos = $this->getDoctrine()
                ->getRepository('UsuariosBundle:Hijo')
                ->findHijos();

        $response = $this->render(
                'UsuariosBundle:Hijo:list.xls.twig', array('hijos' => $hijos)
        );
        $response->headers->set('Content-Type', 'text/vnd.ms-excel; charset=utf-8');
        $response->headers->set('Content-Disposition', 'attachment; filename="export-hijos.xls"');
        return $response;
    }
}

src/Richpolis/UsuariosBundle/Resources/views/Hijo/edit.html.twig
{% extends '::admin.html.twig' %}

{% block body %}
<div class="container">
    <h1>Editar hijo</h1>
    <form action="{{ path('hijos_update',{'id': entity.id }) }}" method="post" {{ form_enctype(form) }}>
        <input name="_method" value="put" type="hidden"/>
        {{ form_errors(form) }}
         <fieldset>
            <legend>Datos personales</legend>
             <div class="form-group">
                 {{ form_row(form.nombre) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.apodo) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.usarApodo)}}
             </div>
             <div class="form-group">
                 {{ form_row(form.sexo)}}
             </div>
             <div class="form-group">
                 {{ form_row(form.fechaNacimiento) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.biografia) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.file) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.papa) }}
             </div>
        </fieldset>
        <hr/>
        
        <div class="container">
        <a href="{{path('hijos')}}" class="btn btn-success">Regresar</a>
        <input type="submit" class="btn btn-primary" name="botonGuardar" id="botonGuardar" value="Guardar"/>
        </div>
        {{ form_rest(form) }}
    </form>
</div>
{% endblock %}

src/Richpolis/UsuariosBundle/Resources/views/Hijo/index.html.twig
{% extends '::admin.html.twig' %}

{% block body -%}
    {% include 'FrontendBundle:Default:navegador.html.twig' with {'tabActive': 'hijos' } %}
    <div class="tab-content">
        <div id="hijos" class="tab-pane active">
            <div class="container text-left">
                <form action="{{path('hijos')}}" class="navbar-form navbar-left pull-center" role="search">
                    <div class="form-group">
                        <input class="form-control" placeholder="Buscar Hijo" type="text" name="buscar">
                    </div>
                    <button type="submit" class="btn btn-default">
                        Buscar
                    </button>
                </form>
            </div>
            <div class="container text-center">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        Hijos
                    </div>
                    <!-- Table -->
                    <table class="table">
                        <thead>
                        <tr>
                            <th class="text-center">
                                Papa/Mama
                            </th>
                            <th class="text-center">
                                Nombre
                            </th>
                            <th class="text-center">
                                Apodo
                            </th>
                            <th class="text-center">
                                Imagen
                            </th>
                            <th class="text-center">
                                Accion
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for hijo in pagination %}
                        <tr>
                            <td>
                                {{ hijo.papa }}
                            </td>
                            <td>
                                {{ hijo.nombre }}
                            </td>
                            <td>
                                {{ hijo.apodo }}
                            </td>
                            <td>
                                <img src="{{constant('Richpolis\\FrontendBundle\\Controller\\DefaultController::RUTA_WEB')}}{{ hijo.thumbnailWebPath }}" style="max-width: 120px;" />
                            </td>
                            <td>
                                <a href="{{ url('hijos_show', { 'id' : hijo.id }) }}" class="btn btn-success">Ver</a>
                                <a href="{{ url('hijos_edit', { 'id' : hijo.id }) }}" class="btn btn-info">Editar</a>
                                <!--a href="javascript: if (confirm('Desea elminar el hijo seleccionado?')) { location.href='{{ url('hijos_delete', { 'id' : hijo.id }) }}';}" class="btn btn-danger">Eliminar</a-->
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="container">
                    <a href="{{ path('hijos_new') }}" class="btn btn-primary pull-left">Nuevo Hijo</a>
                    <a href="{{ path('hijos_export') }}" class="btn btn-default pull-right">Exportar</a>
                </div>
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            </div>
        </div>
        
    </div>
    <div class="container text-center">
        <h5>
            Baby Story
        </h5>
    </div>
{% endblock %}

src/Richpolis/UsuariosBundle/Resources/views/Hijo/list.xls.twig
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                Papa/Mama
            </th>
            <th>
                Nombre
            </th>
            <th>
                Apodo
            </th>
            <th>
                Usar Apodo
            </th>
            <th>
                Fecha nacimiento
            </th>
             <th>
                Biografia
            </th>
            <th>
                Alta
            </th>
             <th>
                Actualizacion
            </th>
        </tr>
    </thead>
    <tbody>
        {% for hijo in hijos %}
            <tr>
                <td>
                    {{ hijo.papa }}
                </td>
                <td>
                    {{ hijo.nombre }}
                </td>
                <td>
                    {{ hijo.apodo }}
                </td>
                <td>
                    {% if hijo.usarApodo %}
                        Si
                    {% else %}
                        No
                    {% endif %}    
                </td>
                <td>
                    {{ hijo.fechaNacimiento | date('d-m-Y') }}
                </td>
                <td>
                    {{ hijo.biografia }}
                </td>
                <td>
                    {{ hijo.createdAt | date('d-m-Y') }}
                </td>
                <td>
                    {{ hijo.updatedAt | date('d-m-Y') }}
                </td>
            </tr>
        {% endfor %}
    </tbody> 
</table>

src/Richpolis/UsuariosBundle/Resources/views/Hijo/new.html.twig
{% extends '::admin.html.twig' %}

{% block body %}
<div class="container">
    <h1>Editar hijo</h1>
    <form action="{{ path('hijos_create') }}" method="post" {{ form_enctype(form) }}>
        {{ form_errors(form) }}
        <fieldset>
            <legend>Datos personales</legend>
             <div class="form-group">
                 {{ form_row(form.nombre) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.apodo) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.usarApodo)}}
             </div>
             <div class="form-group">
                 {{ form_row(form.sexo)}}
             </div>
             <div class="form-group">
                 {{ form_row(form.fechaNacimiento) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.biografia) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.file) }}
             </div>
             <div class="form-group">
                 {{ form_row(form.papa) }}
             </div>
        </fieldset>
        <hr/>
        
        <div class="container">
        <a href="{{path('hijos')}}" class="btn btn-success">Regresar</a>
        <input type="submit" class="btn btn-primary" name="botonGuardar" id="botonGuardar" value="Guardar"/>
        </div>
        {{ form_rest(form) }}
    </form>
</div>
{% endblock %}

src/Richpolis/UsuariosBundle/Resources/views/Hijo/show.html.twig
{% extends '::admin.html.twig' %}

{% block body -%}
    <div class="container">
    <h2>Hijo</h2>
    <table class=" table table-striped"> 
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apodo</th>
            <th>Biografia</th>
            <th>Imagen</th>
        </tr>
     </thead>
     <tbody>
            <tr>
                <td>{{entity.nombre}}</td>
                <td>{{entity.apodo}}</td>
                <td>{{entity.biografia}}</td>
                <td>
                    {% if entity.imagen | length > 0 %}
                    <img src="{{constant('Richpolis\\FrontendBundle\\Controller\\DefaultController::RUTA_WEB')}}{{entity.thumbnailWebPath}}" />    
                    {% else %}    
                    <img src="{{asset('images/sin-imagen-usuario.png')}}"/>
                    {% endif %}
                </td>
            </tr>
     </tbody>   
    </table>      
    <h1>Papa/Mama</h1>
    <table class="record_properties table table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Email</th>
                <th>Ciudad</th>
            </tr>
            <tr>
                <td>{{ entity.papa.id }}</td>
                <td>{{ entity.papa.username }}</td>
                <td>{{ entity.papa.email }}</td>
                <td>{{ entity.papa.ciudad }}</td>
            </tr>
            <tr>
                <th>Es</th>
                <th>Biografia</th>
                <th>Ser {{entity.papa.stringSexo}}</th>
                <th>Imagen</th>
            </tr>
            <tr>
                <td>{{ entity.papa.stringSexo }}</td>
                <td>{{ entity.papa.biografia }}</td>
                <td>{{ entity.papa.serMadre }}</td>
                <td>
                    {% if entity.papa.imagen | length > 0 %}
                    <img src="{{constant('Richpolis\\FrontendBundle\\Controller\\DefaultController::RUTA_WEB')}}{{entity.papa.thumbnailWebPath}}" />    
                    {% else %}    
                    <img src="{{asset('images/sin-imagen-usuario.png')}}"/>
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    
</div>
<p> &nbsp; </p>
<div class="container text-center">            
<ul class="record_actions list-inline">
    <li>
        <a href="{{ path('hijos') }}" class="btn btn-primary">
            Regresar
        </a>
    </li>
    <li>
        <a href="{{ path('hijos_edit', { 'id': entity.id }) }}" class="btn btn-success">
            Editar
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
</div>    
{% endblock %}